force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inadimplente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status do cliente</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bloqueado</fullName>
            </value>
            <value>
                <fullName>Liberado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parcela__c/Parcela__c.object-meta.xml
<CustomObject>
    <label>Parcela</label>
    <nameField>
        <label>Número da Parcela</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcelas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Parcela__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parcelas</relationshipLabel>
    <relationshipName>Parcelas_Cliente</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Parcela__c/fields/Data_Vencimento__c.field-meta.xml
<CustomField>
    <fullName>Data_Vencimento__c</fullName>
    <label>Data_Vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Parcela__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em aberto</fullName>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Atrasado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parcela__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/NegociarCobrancaController.cls
public with sharing class NegociarCobrancaController {
    
    //método para buscar as parcelas não pagas que estejam relacionadas a conta do Case.
    @AuraEnabled(cacheable=true)
    public static List<Parcela__c> buscarParcelas(Id caseId){

        //busca a conta relacionada ao Case
        Case c = [SELECT AccountId FROM Case WHERE Id = :caseId];

        //retorna as parcelas da conta que ainda não foram pagas ordenadas pela data de vencimento
        return [
            SELECT Id, Valor__c, Data_Vencimento__c, Status__c 
            FROM Parcela__c
            WHERE Account__c = :c.AccountId
            AND Status__c  != 'Pago'
            ORDER BY Data_Vencimento__c ASC
        ];
    }

    //método para quitar as parcelas selecionadas e liberar a conta, os pedidos e o Case
    @AuraEnabled
    public static void quitarDepoisLiberar(Id caseId, List<Id> parcelaIds){
        //validação para não processar nada sem que uma parcela seja selecionada
        if(parcelaIds == null || parcelaIds.isEmpty()){
            throw new AuraHandledException('É necessário selecionar pelo menos uma parcela.');
        }

        //busca a conta relacionada ao Case
        Case c = [SELECT AccountId FROM Case WHERE Id = :caseId];

        //busca as parcelas selecionadas para serem atualizadas
        List<Parcela__c> parcelas = [SELECT Id, Status__c FROM Parcela__c WHERE Id IN :parcelaIds];

        //atualiza o status das parcelas selecionadas para pago
        for(Parcela__c parcela : parcelas){
            parcela.Status__c = 'Pago';
        }
        update parcelas;

        //verificar se ainda há parcelas em aberto para não fechar o case com parcelas sem quitar
        Integer parcelasAbertas = [ SELECT COUNT() FROM Parcela__c WHERE Account__c = :c.AccountId AND Status__c != 'Pago'];

        if(parcelasAbertas == 0){
            //depois de quitado, altera o status da conta para ativo
            Account conta = new Account(Id = c.AccountId, Status__c = 'Ativo');
            update conta;

            //busca os pedidos que foram bloqueados relacionados à conta
            List<Order> pedidos = [SELECT Id, Status__c FROM Order WHERE AccountId = :c.AccountId AND Status__c = 'Bloqueado'];

            //libera os pedidos novamente
            for(Order pedido : pedidos){
                pedido.Status__c = 'Liberado';         
            }
            update pedidos;

            //fecha o Case de cobrança após quitado
            update new Case(Id = caseId, Status = 'Closed');
        }       
    }
}